# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateField(default=datetime.datetime(2017, 7, 9, 8, 54, 32, 72189, tzinfo=utc)),
        ),
    ]
