# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 10:08
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+254727843600', max_length=128),
            preserve_default=False,
        ),
    ]
